const GameData = [
    {
        id: 1,
        gameName: "Coin Pusher",
        tags: ["virtual"],
        category: "Next Gen",
        thumbnail: "https://res.cloudinary.com/detatjujs/image/upload/v1712826703/coin-pusher_1000x1000_en_aey0mh.png",
        iframeUrl: "https://example.com/game1-iframe-url",
        demoUrl: "https://example.com/game1-demo-url",
        isFeatured: true,
      },
      {
        id: 2,
        gameName: "KM Virtual Animal Race",
        tags: ["virtual", "sports"],
        category: "Next Gen",
        thumbnail: "https://res.cloudinary.com/detatjujs/image/upload/v1712826702/animal-race_1000x1000_en_w7inev.jpg",
        iframeUrl: "https://example.com/game2-iframe-url",
        demoUrl: "https://example.com/game2-demo-url",
        isFeatured: true,
      },      
      {
        id: 3,
        gameName: "KM Virtual Treadmill Racing",
        tags: ["virtual", "sports"],
        category: "Next Gen",
        thumbnail: "https://res.cloudinary.com/detatjujs/image/upload/v1712826702/treadmill-racing_1000x1000_en_mfmxzw.jpg",
        iframeUrl: "https://example.com/game2-iframe-url",
        demoUrl: "https://example.com/game2-demo-url",
        isFeatured: true,
      },
      {
        id: 4,
        gameName: "Minesweeper",
        tags: [],
        category: "Next Gen",
        thumbnail: "https://res.cloudinary.com/detatjujs/image/upload/v1712826701/mine-sweeper_1000x1000_en_xuaesi.jpg",
        iframeUrl: "https://example.com/game2-iframe-url",
        demoUrl: "https://example.com/game2-demo-url",
        isFeatured: true,
      },
      {
        id: 5,
        gameName: "Sugar Blast",
        tags: [],
        category: "Slot",
        thumbnail: "https://res.cloudinary.com/detatjujs/image/upload/v1712828695/sugar-blast_1000x1000_en_wmodzo.jpg",
        iframeUrl: "https://example.com/game2-iframe-url",
        demoUrl: "https://example.com/game2-demo-url",
        isFeatured: true,
      },
      {
        id: 6,
        gameName: "Gems of Valhalla",
        tags: [],
        category: "Slot",
        thumbnail: "https://res.cloudinary.com/detatjujs/image/upload/v1712828672/gems-of-valhalla_500x500_en_jn5tkj.png",
        iframeUrl: "https://example.com/game2-iframe-url",
        demoUrl: "https://example.com/game2-demo-url",
        isFeatured: true,
      },
      {
        id: 7,
        gameName: "Baccarat",
        tags: ['card'],
        category: "Classics",
        thumbnail: "https://res.cloudinary.com/detatjujs/image/upload/v1712828960/Baccarat_1000x1000_en_h2qema.jpg",
        iframeUrl: "https://example.com/game2-iframe-url",
        demoUrl: "https://example.com/game2-demo-url",
        isFeatured: true,
      },
      {
        id: 8,
        gameName: "KM Power Ball",
        tags: ['lottery'],
        category: "Classics",
        thumbnail: "https://res.cloudinary.com/detatjujs/image/upload/v1712829079/km-power-ball_1000x1000_en_brpc6v.jpg",
        iframeUrl: "https://example.com/game2-iframe-url",
        demoUrl: "https://example.com/game2-demo-url",
        isFeatured: true,
      },
]


export default GameData;